#--------------------------------------------------------------------------------
# Workflow configuration
#--------------------------------------------------------------------------------

  name: Build
  on:
    push:               # Run on push
    pull_request:       # Run on pull-request
  
  #--------------------------------------------------------------------------------
  # Define application name & version
  #--------------------------------------------------------------------------------
  
  env:
    VERSION: "1.0.0"
    EXECUTABLE: "TooRun"
    APPLICATION: "TooRun"
    QMAKE_PROJECT: "toorun.pro"
  
  #--------------------------------------------------------------------------------
  # Workflow jobs
  #--------------------------------------------------------------------------------
  
  jobs:  
    #
    # Windows build
    #
    build-windows:
      runs-on: windows-latest
      steps:
        #
        # Checkout the repository
        #
        - name: Checkout repository and submodules
          uses: actions/checkout@v3
          with:
            submodules: recursive
        
        #
        # Configure MSVC
        #
        - name: Configure MSVC
          uses: ilammy/msvc-dev-cmd@v1
          with:
            arch: x64
            spectre: true
  
        #
        # Install Qt
        #
        - name: Install Qt
          uses: jurplel/install-qt-action@v3
          with:
            cache: true
            version: '5.15.2'
            
        #
        # Compile application
        #
        - name: Compile
          run: |
               qmake ${{env.QMAKE_PROJECT}}
               nmake
               
        # - name: Find and package EXE
        #   run: |
        #     mkdir release
        #     copy *.exe release/  # Copy the EXE to the release folder
        #     dir release  # Show the contents for debugging
        #   shell: cmd
        - name: Upload EXE as an artifact
          uses: actions/upload-artifact@v4
          with:
            name: TooRun-${{ github.run_id }}
            path: release/*.exe

        # - name: Upload EXE to GitHub Releases (Only on Tags)
        #   if: startsWith(github.ref, 'refs/tags/')
        #   uses: softprops/action-gh-release@v1
        #   with:
        #     files: debug/*.exe  # Upload all EXE files in the release folder
        #   env:
        #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Auto-generated token for GitHub Actions
        